### ISSUE TITLE
Dr. Silva "Event Package"

### ISSUE THREAD

**Issue by comfortleaf** [comfortleaf/Legacy-WP#39]
Dr. Silva's Ultra Wellness Center

Leaving the Nov 16th, 2018
Event is on November 19th 2018

75 to 100 doctors (all niches)
Pass information / product samples
Promote product awareness

---

- [x] Dr. Silva Business Cards #34 
- [x] Product to Sell ( #54 Lotions, #55 Tinctures, #57 Gummies)
- [x] Text for more info SMS #16
