### ISSUE TITLE
Veterans Event

### ISSUE THREAD

**Issue by comfortleaf** [comfortleaf/Legacy-WP#40]
Veterans 
Event is on November 10th, 2018
Pass information / product samples
Promote product awareness

---

- [ ] Product to Sell ( #54 Lotions, #55 Tinctures, #57 Gummies)
- [ ] Educational Brochure for Events #61
- [ ] Stickers #31 
- [ ] Standing Banner #47 
- [ ] Throw Table Cloth #48 
- [ ] Text for more info SMS #16 
- [ ] Mug for Comfort Leaf #62
- [ ] Fridge Magnet #58
- [ ] Table Tent "Card" #59
- [ ] Event Tent (Might be overkill for this event.) #49 
- [ ] Presentation Folder with Info on CBD #60

**Comment by comfortleaf** [comment]
The event was to close & CF was not prepared.
