### ISSUE TITLE
NORML Event

### ISSUE THREAD

**Issue by comfortleaf** [comfortleaf/Legacy-WP#67]
January 25th, 2019 

-

- [ ] Product to Sell ( #54 Lotions, #55 Tinctures, #57 Gummies, #56 Vape Cartridges)
- [ ] Educational Brochure for Events #61
- [ ] Stickers #31 
- [ ] Standing Banner #47 
- [ ] Throw Table Cloth #48 
- [ ] Text for more info SMS #16 
- [ ] Mug for Comfort Leaf #62
- [ ] Fridge Magnet #58
- [ ] Table Tent "Card" #59
- [ ] Event Tent (Might be overkill for this event.) #49 
- [ ] Presentation Folder with Info on CBD #60

**Comment by comfortleaf** [comment]
![comfortleaf-display-booth](https://user-images.githubusercontent.com/44081118/47769526-982a5280-dcb2-11e8-9fd7-e53c6d772ff6.jpg)
